__author__ = 'Andrew Hawker <andrew.r.hawker@gmail.com>'

INT8     = '>B'
INT16    = '>h'
UINT16   = '>H'
INT32    = '>i'
UINT32   = '>I'
INT64    = '>q'
UINT64   = '>Q'
FLOAT    = '>f'
DOUBLE   = '>d'
UINT128  = '>QQ'

VARIABLE_UINT32  = '>{0:d}I'
ID_CREATION_PAIR = '>IB'